### PR TITLE
Fix FileGator 7.13.4 session migrate incompatibility in Hestia

### LINKED ISSUE #5240: [Bug] Latest filegator version causing error 500
### Describe the bug

After updating to the latest FileGator version bundled with HestiaCP, the file manager returns an HTTP 500 error.

The issue appears to be related to the session storage implementation located in:
/usr/local/hestia/web/fm/backend/Services/Session

As a temporary workaround, I copied the Session directory from a previous working installation, and the file manager started working again.

However, if I run:

v-delete-sys-filemanager
v-add-sys-filemanager

the problem reappears.

Expected behavior
The File Manager should load normally without triggering a PHP fatal error.

### Tell us how to replicate the bug

Install or update HestiaCP with the latest bundled FileGator.

Access the File Manager (/fm/).

The interface returns HTTP 500.

### Which components are affected by this bug?

Control Panel Backend, Control Panel Web Interface

### Hestia Control Panel Version

1.9.4

### Operating system

Ubuntu 24

### Log capture

```shell
2026/03/04 21:30:48 [error] 2887#0: *37 FastCGI sent in stderr:
"PHP message: PHP Fatal error: Class Filegator\Services\Session\Adapters\SessionStorage
contains 1 abstract method and must therefore be declared abstract or implement the
remaining methods (Filegator\Services\Session\SessionStorageInterface::migrate)
in /usr/local/hestia/web/fm/backend/Services/Session/Adapters/SessionStorage.php on line 18"
while reading response header from upstream, client: XXX.XXX.XXX, server: _, request: "GET /fm/ HTTP/2.0",
upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "XXXX:8083", referrer: "https://xxxx:8083/list/web/"
```

### PR DESCRIPTION
**Pull request by sahsanu**
FileGator 7.13.4 introduced the migrate() method on the session storage, and Hestia’s bundled SessionStorage adapter was not updated accordingly. As a result, FileGator attempted to call migrate() on the storage, which did not exist in Hestia’s version, causing a 500 Internal Server Error.

This commit adds the missing migrate($destroy = false, $lifetime = null) method to the SessionStorage adapter and proxies the call to the underlying Session instance, restoring compatibility with FileGator 7.13.4 and preventing the 500 error.

Fixes #5240

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

File: install/deb/filemanager/filegator/backend/Services/Session/Adapters/SessionStorage.php [hunk 1]
```diff
@@ -29,7 +29,7 @@ public function init(array $config = []) {
 		if (!$this->getSession()) {
 			$handler = $config["handler"];
 			$session = new Session($handler());
-			//$session->setName('filegator');
+			//$session->setName("filegator");
```
Comment (n3b0r) [inline install/deb/filemanager/filegator/backend/Services/Session/Adapters/SessionStorage.php:32]: Adding this causes the following error:

```
2026/05/04 15:33:07 [error] 409#0: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 53; PHP message: PHP Fatal error:  Uncaught LogicException: Cannot change the name of an active session. in /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Session/Storage/Proxy/AbstractProxy.php:117
Stack trace:
#0 /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(237): Symfony\Component\HttpFoundation\Session\Storage\Proxy\AbstractProxy->setName()
#1 /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Session/Session.php(225): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->setName()
#2 /usr/local/hestia/web/fm/backend/Services/Session/Adapters/SessionStorage.php(32): Symfony\Component\HttpFoundation\Session\Session->setName()
#3 /usr/local/hestia/web/fm/backend/App.php(33): Filegator\Services\Session\Adapters\SessionStorage->init()
#4 /usr/local/hestia/web/fm/dist/index.php(50): Filegator\App->__construct()
#5 {main}
  thrown in /usr/local/hestia/web/fm/vendor/symfony/http-foundation/Session/Storage/Proxy/AbstractProxy.php on" while reading response header from upstream, client: X.X.X.X, server: _, request: "GET /fm/ HTTP/2.0", upstream: "fastcgi://unix:/run/hestia-php.sock:", host: "REDACTED", referrer: "https://REDACTED/list/user/"
```


So it's not needed.

Comment (sahsanu) [reply install/deb/filemanager/filegator/backend/Services/Session/Adapters/SessionStorage.php:32]: Sorry, but I don't see any relation between the commented line with the warning/error you get. Indeed that is fixed in another PR #5286
