### PR TITLE
#1286 fix javascript database name

### LINKED ISSUE #1286: Incorrect database name/username preview
### In a few words, please describe the issue that you're experiencing:
The previews showing upon Database creation are incorrect if they include the prefix.

### What steps did you take when the issue occured? 
1. Create a database with **username_** in the database name or username as prefix
2. The preview behind the field shows it without prefix
3. Click Save
4. The database has been created with prefix, opposed to the preview

Hereby the preview without the literal **username_** prefix in the input:
test1

However, as soon as it contains the literal **username_** prefix in the input, the preview shows as such:
test2

But upon creation, it saves it like this:
test3

test4

### Expected behavior:
Either the preview should be correct (**username_username_name**), or the database should be saved with the name and username that showed in the preview (**username_name**).

### Operating system:
Debian 10

### Hestia Control Panel version:
1.2.4

### PR DESCRIPTION
**Pull request by jaapmarcus**
Fixes #1286 

- Synced behavoir with /add/db and /edit/db 
- Fixed issues in #1286 as reported

### CODE REVIEW

File: web/edit/db/index.php [hunk 1]
```diff
@@ -53,7 +53,7 @@
     
     // Change database user
     if (($v_dbuser != $_POST['v_dbuser']) && (empty($_SESSION['error_msg']))) {
-        $v_dbuser = preg_replace("/^".$user."_/", "", $_POST['v_dbuser']);
+        //$v_dbuser = preg_replace("/^".$user."_/", "", $_POST['v_dbuser']);
```
Comment (ScIT-Raphael) [inline web/edit/db/index.php]: I would suggest to remove the code instead comment it - code history will be provided over github.

**Review by ScIT-Raphael — CHANGES_REQUESTED** [review]
