### PR TITLE
Fix: DNS cluster expected return code instead of string

### LINKED ISSUE #3707: [Bug] Unable to sync text records containig "
### Describe the bug

Add a new DNS record look like:

`_dmarc  14400   IN      TXT             "v=DMARC1; p=policy; pct=100"`

And sync up the dns cluster:

root@dev:/usr/local/hestia/data/queue# bash ./dns-cluster.pipe 
Error: monitor.xxxx.nu connection failed (record sync)

### Tell us how to replicate the bug

Add a new DNS record look like:

`_dmarc  14400   IN      TXT             "v=DMARC1; p=policy; pct=100"`

And sync up the dns cluster:

root@dev:/usr/local/hestia/data/queue# bash ./dns-cluster.pipe 
Error: monitor.xxxx.nu connection failed (record sync)

### Which components are affected by this bug?

Control Panel Command Line Interface

### Hestia Control Panel Version

1.7.7+

### Operating system

N/A

### Log capture

```shell
2023-06-21 11:29:51 v-insert-dns-record  'xxxx' 'xxxxx' 'ID='17' RECORD='_domainkey' TYPE='TXT' PRIORITY='' VALUE='\"t=y; o=~;\"' SUSPENDED='no' TIME='08:07:58' DATE='2023-06-21'' 'no'
```

### PR DESCRIPTION
**Pull request by jaapmarcus**
DNS cluster syncing / set up requires always an numeric code in return. 

https://github.com/hestiacp/hestiacp/blob/8c26daac3469f2d5e021080d19901553d1801ff0/func/remote.sh#L50

In the past by default the text was shown if an error code was generated if the users tries to connect  with an incorrect  password/key or ip is not allowed

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Closes: #3707

File: web/inc/helpers.php [hunk 1]
```diff
@@ -50,6 +51,7 @@ function exit_code_to_http_code(int $exit_code, int $default = 400): int {
 		case E_UNSUSPENDED:
 		case E_FORBIDEN:
 		case E_FORBIDDEN:
+		case E_API_DISABLED:
 			return 401;
```
Comment (ScIT-Raphael) [inline web/inc/helpers.php:55]: alignment of return should be checked.

**Review by ScIT-Raphael — CHANGES_REQUESTED** [review]

File: web/inc/helpers.php (hunk 1 above)
Comment (jaapmarcus) [reply web/inc/helpers.php:55]: Screenshot 2023-06-21 at 14 46 46

Looks fine and consistent to me...

**Review by ScIT-Raphael — APPROVED** [review]
