### PR TITLE
fix: Make sure MariaDB configures correct lc-messages-dir

### LINKED ISSUE #4712: [Bug] Languages PHPmyadmin not working due to missing symlink
### Describe the bug

https://forum.hestiacp.com/t/no-russian-language-hestia-control-panel-v1-9-0-beta1/17286/12

### Tell us how to replicate the bug

Missing symlink needs to be created (MariaDB only)

### Which components are affected by this bug?

Database (MariaDB, MySQL, PostgreSQL)

### Hestia Control Panel Version

1.9

### Operating system

N/A.

### Log capture

_No response_

### PR DESCRIPTION
**Pull request by rjd22**
Should correctly fix #4712. Note: We should really separate the mariadb and mysql installation configurations.

### CODE REVIEW

File: install/hst-install-debian.sh [hunk 1]
```diff
@@ -1776,6 +1776,7 @@ if [ "$mysql" = 'yes' ] || [ "$mysql8" = 'yes' ]; then
 	fi
 
 	if [ "$mysql_type" = 'MariaDB' ]; then
+		sed -i 's|/usr/share/mysql|/usr/share/mariadb|g' /etc/mysql/my.cnf
```
Comment (jaapmarcus) [inline install/hst-install-debian.sh:1779]: We also need to update the same for Ubuntu..

**Review by jaapmarcus — APPROVED** [review]
